[package]
name = "rw3d_net"
description = "Witcher 3 network protocol implementation"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
shrinkwraprs.workspace = true
strum.workspace = true
strum_macros.workspace = true