name: check-build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true
    - name: Build with Cargo
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=x86_64-pc-windows-msvc
    - name: Run tests
      run: cargo test --verbose
