name: draft-release

on:
  push:
    tags: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true
    - name: Build with Cargo
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target=x86_64-pc-windows-msvc
    - name: Zip the executable
      uses: papeloto/action-zip@v1
      with:
        files: "target/x86_64-pc-windows-msvc/release/rw3d_cli.exe"
        dest: "Rusty Witcher 3 Debugger CLI.zip"
    - name: Create draft release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "Rusty Witcher 3 Debugger CLI.zip"
        draft: true
        generateReleaseNotes: true
